// AUTHENTICATION
export const AUTH_USER = 'AUTH_USER';
export const AUTH_LOADING = 'AUTH_LOADING';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_LOGOUT_ERROR = 'AUTH_LOGOUT_ERROR';
export const AUTH_CHECK_TOKEN = 'AUTH_CHECK_TOKEN';
export const AUTH_TOKEN_ERROR = 'AUTH_TOKEN_ERROR';

// NOTES
export const GET_ALL_NOTES = 'GET_ALL_NOTES';
export const GET_USER_NOTES = 'GET_USER_NOTES';
export const NOTES_LOADING = 'NOTES_LOADING';
export const NOTES_ERROR = 'NOTES_ERROR';
export const DELETE_NOTE = 'DELETE_NOTE';
